[package]
name = "retcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
hex = "0.4.3"
indicatif = "0.17.11"
sha2 = "0.10.8"
sudo = "0.6.0"
